name: 'Accessibility Tests'
on: push
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          workingDir: inflearn-design-system-story-board
      - uses: actions/setup-node@v3
        with:
          workingDir: inflearn-design-system-story-board
          node-version-file: '.nvmrc'
      - name: Install dependencies
        working-directory: inflearn-design-system-story-board
        run: yarn
      - name: Install Playwright
        working-directory: inflearn-design-system-story-board
        run: npx playwright install --with-deps
      - name: Build Storybook
        working-directory: inflearn-design-system-story-board
        run: yarn build-storybook --quiet
      - name: Serve Storybook and run tests
        working-directory: inflearn-design-system-story-board
        run: |
          npx concurrently -k -s first -n "SB,TEST" -c "magenta,blue" \
            "npx http-server storybook-static --port 6006 --silent" \
            "npx wait-on tcp:6006 && yarn test-storybook"